// Responsive photo sources from src/data/images.json (generated by scripts/images.mjs).
// Phones get at most the 960 px file: one media-query source for phones, one for wider screens.
// The hero preload in Base.astro uses the same function, so preload and <picture> always match.
import images from '../data/images.json';

export const PHONE_MQ = '(max-width: 700px)';
export const WIDE_MQ = '(min-width: 701px)';
export const PHONE_MAX = 960;

interface Entry {
  widths: number[];
  width: number;
  height: number;
}

export function photo(name: string) {
  const e = (images.photos as Record<string, Entry>)[name];
  if (!e) throw new Error(`No photo named ${name}`);
  const phone = e.widths.filter((w) => w <= PHONE_MAX);
  const set = (ext: string, widths = e.widths) => widths.map((w) => `/images/photos/${name}-${w}.${ext} ${w}w`).join(', ');
  return {
    width: e.width,
    height: e.height,
    fallback: `/images/photos/${name}-${e.widths[0]}.jpg`,
    /** srcset for phones (capped) and for wider screens */
    phone: (ext: string) => set(ext, phone),
    wide: (ext: string) => set(ext),
  };
}

export function logo(name: string) {
  const e = (images.logos as Record<string, { width: number; height: number }>)[name];
  if (!e) throw new Error(`No logo named ${name}`);
  return { ...e, webp: `/images/logos/${name}.webp`, png: `/images/logos/${name}.png` };
}
