// Presentation content for the v7 design: which photo goes where, the country
// descriptors, the featured projects and the capability and decade panels.
// Facts come from projects.json and company.json; this file only chooses and phrases.
import { projects, projectBySlug, projectUrl, countries, type Project, type Sector } from './data';

/** Photos in public/images/photos (generated by scripts/images.mjs). None shows a specific company project. */
export type PhotoName =
  | 'tower-sky'
  | 'tower-mono'
  | 'desert-lines'
  | 'distribution-pole'
  | 'offshore-platform'
  | 'construction-site'
  | 'engineering-drawings'
  | 'site-engineer'
  | 'industrial-plant'
  | 'substation'
  | 'power-channel'
  | 'pipeline'
  | 'transmission-towers';

export interface CountryMeta {
  region: string;
  descriptor: string;
  photo: PhotoName;
}

export const COUNTRY_META: Record<string, CountryMeta> = {
  pakistan: { region: 'Asia', descriptor: 'Headquarters · Transmission & infrastructure', photo: 'power-channel' },
  libya: { region: 'North Africa', descriptor: 'Transmission & oil-sector power', photo: 'desert-lines' },
  'saudi-arabia': { region: 'Middle East', descriptor: 'Transmission & fibre networks', photo: 'transmission-towers' },
  iraq: { region: 'Middle East', descriptor: 'High-voltage transmission', photo: 'tower-mono' },
  malaysia: { region: 'Asia', descriptor: '500 kV transmission', photo: 'substation' },
  mozambique: { region: 'Africa', descriptor: 'HVDC transmission', photo: 'tower-sky' },
  iran: { region: 'Middle East', descriptor: 'High-voltage transmission', photo: 'distribution-pole' },
};

export function countryMeta(slug: string): CountryMeta {
  const m = COUNTRY_META[slug];
  if (!m) throw new Error(`No country meta for ${slug}`);
  return m;
}

/** Order used on the Home page and Global presence (headquarters first, then by record). */
export const PRESENCE_ORDER = ['pakistan', 'libya', 'saudi-arabia', 'iraq', 'malaysia', 'mozambique', 'iran'].filter((s) =>
  countries.some((c) => c.slug === s),
);

const SECTOR_PHOTOS: Record<Sector, PhotoName[]> = {
  transmission: ['tower-mono', 'desert-lines', 'tower-sky', 'transmission-towers'],
  substation: ['substation'],
  distribution: ['distribution-pole'],
  industrial: ['industrial-plant'],
  'oil-and-gas-electrical': ['offshore-platform', 'industrial-plant'],
  civil: ['construction-site', 'power-channel', 'engineering-drawings'],
  other: ['pipeline', 'site-engineer'],
};

/** A generic photo for a project, chosen by sector (stable per project). Never a photo of the project itself. */
export function projectPhoto(p: Project): PhotoName {
  const list = SECTOR_PHOTOS[p.sector];
  let h = 0;
  for (const ch of p.slug) h = (h * 31 + ch.charCodeAt(0)) >>> 0;
  return list[h % list.length]!;
}

export interface Slide {
  tag: string;
  title: string;
  href: string;
  photo: PhotoName;
}

const card = (slug: string, title: string, photo: PhotoName): Slide => {
  const p = projectBySlug(slug);
  return { tag: p.country, title, href: projectUrl(p), photo };
};

export const HERO_SLIDES: Slide[] = [
  card('benghazi-eastern-border-220-kv-double-circuit-lines-750-km', 'Benghazi to the Eastern Border: 750 km of 220 kV Transmission', 'tower-mono'),
  card('380-110-kv-overhead-lines-and-fibre-optic-network-makkah-taif-and-madinah', 'Makkah, Taif & Madinah: 380 kV Overhead Network', 'substation'),
  card('barotha-rewat-500-kv-transmission-lines', 'Barotha–Rewat: 500 kV National Grid Transmission', 'distribution-pole'),
  card('nasiriya-wasit-baghdad-400-kv-line-358-km', 'Nasiriya–Baghdad: 358 km of 400 kV Transmission', 'desert-lines'),
];

export const FEATURED: Slide[] = [
  card('benghazi-eastern-border-220-kv-double-circuit-lines-750-km', 'Benghazi–Eastern Border 220 kV Transmission', 'tower-mono'),
  card('380-110-kv-overhead-lines-and-fibre-optic-network-makkah-taif-and-madinah', 'Makkah, Taif & Madinah 380 kV Network', 'substation'),
  card('ghazi-barotha-hydropower-project-civil-works', 'Ghazi-Barotha Hydropower Project', 'power-channel'),
  card('nasiriya-wasit-baghdad-400-kv-line-358-km', 'Nasiriya–Wasit–Baghdad 400 kV Transmission', 'desert-lines'),
  card('samnu-sebha-220-kv-double-circuit-twin-bundle-line', 'Samnu–Sebha 220 kV Transmission', 'tower-sky'),
  card('shoaiba-jeddah-380-kv-overhead-transmission-line', 'Shoaiba–Jeddah 380 kV Transmission', 'transmission-towers'),
  card('pindi-bhattian-faisalabad-motorway-m-3', 'Pindi Bhattian–Faisalabad Motorway (M-3)', 'site-engineer'),
  card('songo-apollo-533-kv-hvdc-transmission-line', 'Songo–Apollo ±533 kV HVDC Transmission', 'distribution-pole'),
  card('larkana-jamshoro-500-kv-transmission-line', 'Larkana–Jamshoro 500 kV Transmission', 'tower-mono'),
];

export const LIBYA_FEATURED: Slide[] = [
  card('samnu-sebha-220-kv-double-circuit-twin-bundle-line', 'Samnu–Sebha: Transmission into the Fezzan', 'desert-lines'),
  card('benghazi-eastern-border-220-kv-double-circuit-lines-750-km', 'Benghazi to the Eastern Border', 'tower-mono'),
  card('hun-wadi-arial-samnu-220-kv-transmission-line', 'Hun–Wadi Arial–Samnu Transmission', 'tower-sky'),
  card('misurata-sirte-220-kv-lines-and-tripoli-ring', 'Misurata–Sirte and the Tripoli Ring', 'transmission-towers'),
  { tag: 'Libya', title: 'Power for the Oil Fields', href: '/projects/libya/?sector=oil-and-gas-electrical#register', photo: 'offshore-platform' },
];

export interface Capability {
  id: string;
  title: string;
  text: string;
  photo: PhotoName;
  href: string;
}

// Anchors match the service sections on /services/
const maxKv = Math.max(...projects.filter((p) => p.sector === 'transmission' && p.voltage_kv !== null && !/HVDC/.test(p.name)).map((p) => p.voltage_kv!));
const minKv = Math.min(...projects.filter((p) => p.sector === 'transmission' && p.voltage_kv !== null).map((p) => p.voltage_kv!));
export const MAX_AC_KV = maxKv;

export const CAPABILITIES: Capability[] = [
  {
    id: 'transmission',
    title: 'Power Transmission',
    text: `Overhead transmission lines from ${minKv} kV to ${maxKv} kV and HVDC, delivered from foundations and tower erection to conductor stringing and complete turnkey lines.`,
    photo: 'tower-mono',
    href: '/services/#transmission',
  },
  {
    id: 'substations',
    title: 'Substations',
    text: 'Construction and civil works for grid substations, from the 500/220 kV substation at Peshawar to substations built with line contracts in Libya.',
    photo: 'substation',
    href: '/services/#substations',
  },
  {
    id: 'distribution',
    title: 'Distribution & Industrial Power',
    text: 'Medium-voltage networks, oil-field electrical systems and live-line maintenance for utilities and energy producers.',
    photo: 'distribution-pole',
    href: '/services/#distribution',
  },
  {
    id: 'civil',
    title: 'Civil Infrastructure',
    text: 'Motorways, bridges, water supply, sewerage and urban development for national and provincial authorities.',
    photo: 'construction-site',
    href: '/services/#civil',
  },
  {
    id: 'telecom',
    title: 'Telecommunications',
    text: 'Fibre-optic and communication networks integrated with high-voltage transmission.',
    photo: 'industrial-plant',
    href: '/services/#telecom',
  },
];

export interface Decade {
  label: string;
  tag: string;
  title: string;
  text: string;
  photo: PhotoName;
}

// Milestones by decade (src/lib/milestones.ts and facts.md). The Home version never names people.
export const DECADES: Decade[] = [
  { label: '1950s', tag: 'Lahore', title: 'Nazir and Company Is Founded', text: 'The company is established in Lahore in 1958.', photo: 'construction-site' },
  {
    label: '1970s',
    tag: 'Iraq & Libya',
    title: 'International Expansion',
    text: 'The company incorporates in 1972 and by the end of the decade is at work in Iraq, Libya, Saudi Arabia and Iran.',
    photo: 'industrial-plant',
  },
  {
    label: '1980s',
    tag: 'Libya & Iraq',
    title: '220 kV and 400 kV Across North Africa and the Middle East',
    text: 'Transmission from Misurata to Sirte and around Tripoli, and the 358 km Nasiriya–Baghdad line.',
    photo: 'tower-mono',
  },
  {
    label: '1990s',
    tag: 'Mozambique & Malaysia',
    title: 'HVDC and 500 kV',
    text: 'The ±533 kV Songo–Apollo HVDC line and 500 kV transmission for Tenaga Nasional.',
    photo: 'substation',
  },
  {
    label: '2000s',
    tag: 'Libya & Pakistan',
    title: '750 km Across Eastern Libya',
    text: "A turnkey 220 kV line from Benghazi to the eastern border, and Barotha–Rewat for Pakistan's national grid.",
    photo: 'desert-lines',
  },
  {
    label: '2010s',
    tag: 'Libya & Saudi Arabia',
    title: 'From the Fezzan to the Holy Cities',
    text: 'Samnu–Sebha for GECOL, and 380 kV transmission around Makkah, Taif and Madinah.',
    photo: 'distribution-pole',
  },
  { label: '2020s', tag: 'Pakistan', title: 'Building New Cities', text: 'Infrastructure for Fatima Jinnah Town, Multan.', photo: 'engineering-drawings' },
];

export const DEFAULT_DECADE = '1980s';

/** Number words for headings ("Seven Countries"). */
export function numberWord(n: number): string {
  return ['Zero', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten'][n] ?? String(n);
}

export interface ClientMark {
  name: string;
  logo?: 'saudi-electricity-company' | 'tenaga-nasional';
  mark?: string;
  sub?: string;
}

// Clients documented in the profiles. Logos only where an official file is held; otherwise a text mark.
export const CLIENT_MARKS: ClientMark[] = [
  { name: 'Saudi Electricity Company', logo: 'saudi-electricity-company' },
  { name: 'Tenaga Nasional Berhad', logo: 'tenaga-nasional' },
  { name: 'General Electricity Company of Libya', mark: 'GECOL', sub: 'General Electricity Co. of Libya' },
  { name: 'National Grid Company of Pakistan', mark: 'NGC', sub: 'National Grid Company of Pakistan' },
  { name: 'Water and Power Development Authority', mark: 'WAPDA', sub: 'Water & Power Development Authority' },
  { name: 'National Highway Authority', mark: 'National Highway Authority', sub: 'Pakistan' },
  { name: 'Arabian Gulf Oil Company', mark: 'Arabian Gulf Oil Company', sub: 'Libya' },
  { name: 'Sirte Oil Company', mark: 'Sirte Oil Company', sub: 'Libya' },
  { name: 'Waha Oil Company', mark: 'Waha Oil Company', sub: 'Libya' },
];
